INSERT INTO GENRES (GENRE_NAME) SELECT 'Комедия'        WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRE_NAME='Комедия');
INSERT INTO GENRES (GENRE_NAME) SELECT 'Драма'          WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRE_NAME='Драма');
INSERT INTO GENRES (GENRE_NAME) SELECT 'Мультфильм'     WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRE_NAME='Мультфильм');
INSERT INTO GENRES (GENRE_NAME) SELECT 'Триллер'        WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRE_NAME='Триллер');
INSERT INTO GENRES (GENRE_NAME) SELECT 'Документальный' WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRE_NAME='Документальный');
INSERT INTO GENRES (GENRE_NAME) SELECT 'Боевик'         WHERE NOT EXISTS (SELECT * FROM GENRES WHERE GENRE_NAME='Боевик');

INSERT INTO MPA (MPA_NAME) SELECT 'G'     WHERE NOT EXISTS (SELECT * FROM MPA WHERE MPA_NAME='G');
INSERT INTO MPA (MPA_NAME) SELECT 'PG'    WHERE NOT EXISTS (SELECT * FROM MPA WHERE MPA_NAME='PG');
INSERT INTO MPA (MPA_NAME) SELECT 'PG-13' WHERE NOT EXISTS (SELECT * FROM MPA WHERE MPA_NAME='PG-13');
INSERT INTO MPA (MPA_NAME) SELECT 'R'     WHERE NOT EXISTS (SELECT * FROM MPA WHERE MPA_NAME='R');
INSERT INTO MPA (MPA_NAME) SELECT 'NC-17' WHERE NOT EXISTS (SELECT * FROM MPA WHERE MPA_NAME='NC-17');

INSERT INTO DIRECTORS (DIRECTOR_NAME) VALUES ('James Cameron');

INSERT INTO films (FILM_NAME,DESCRIPTION,RELEASE_DATE,DURATION,MPA_ID) VALUES ('Dune','dune description','1990-10-01','150','1');


INSERT INTO FILM_DIRECTOR (FILM_ID, DIRECTOR_ID) VALUES ('1','1');
